// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type SignUpDto = {
    /**
     * 이메일
     */
    email: string;
    /**
     * 비밀번호
     */
    password: string;
    /**
     * 이름
     */
    name: string;
    /**
     * 프로필 이미지 URL (선택 사항)
     */
    image?: string;
};

export type UserResponseDto = {
    /**
     * 사용자 ID
     */
    id: string;
    /**
     * 이메일
     */
    email: {
        [key: string]: unknown;
    };
    /**
     * 이름
     */
    name: {
        [key: string]: unknown;
    };
    /**
     * 프로필 이미지 URL
     */
    image: {
        [key: string]: unknown;
    };
    /**
     * 권한 정보
     */
    role: string;
};

export type SignInDto = {
    /**
     * 이메일
     */
    email: string;
    /**
     * 비밀번호
     */
    password: string;
};

export type Role = {
    /**
     * 권한 ID (UUID)
     */
    id: string;
    /**
     * 권한 이름
     */
    name: 'ADMIN' | 'USER' | 'GUEST';
};

export type CreateUserDto = {
    [key: string]: unknown;
};

export type UpdateUserDto = {
    [key: string]: unknown;
};

export type CreateAccountDto = {
    [key: string]: unknown;
};

export type UpdateAccountDto = {
    [key: string]: unknown;
};

export type CreateVerificationTokenDto = {
    [key: string]: unknown;
};

export type UpdateVerificationTokenDto = {
    [key: string]: unknown;
};

export type CreateCourseDto = {
    /**
     * 코스 제목
     */
    title: string;
    /**
     * 코스 가격
     */
    price: number;
    /**
     * 코스 1~2줄 짧은 설명
     */
    shortDescription?: string;
    /**
     * 코스 상세페이지 설명
     */
    description?: string;
    /**
     * 썸네일 이미지 URL
     */
    thumbnailUrl?: string;
    /**
     * 코스 할인 가격
     */
    discountPrice?: number;
    /**
     * 코스 난이도
     */
    level?: string;
    /**
     * 코스 게시 여부
     */
    isPublished?: boolean;
    /**
     * 코스 카테고리 ID 목록
     */
    categoryIds?: Array<string>;
};

export type Account = {
    /**
     * 계정 ID (UUID)
     */
    id: string;
    /**
     * 계정 타입
     */
    type: string;
    /**
     * 제공자 (Provider)
     */
    provider: string;
    /**
     * 제공자측 계정 ID
     */
    providerAccountId: string;
    /**
     * 리프레시 토큰
     */
    refreshToken?: {
        [key: string]: unknown;
    } | null;
    /**
     * 액세스 토큰
     */
    accessToken?: {
        [key: string]: unknown;
    } | null;
    /**
     * 토큰 만료 시간
     */
    expiresAt?: {
        [key: string]: unknown;
    } | null;
    /**
     * 토큰 타입
     */
    tokenType?: {
        [key: string]: unknown;
    } | null;
    /**
     * 권한 범위 (Scope)
     */
    scope?: {
        [key: string]: unknown;
    } | null;
    /**
     * ID 토큰
     */
    idToken?: {
        [key: string]: unknown;
    } | null;
    /**
     * 사용자 ID
     */
    userId: string;
    /**
     * 사용자 정보
     */
    user: User;
};

export type Lecture = {
    /**
     * 강의(레슨) ID (UUID)
     */
    id: string;
    /**
     * 강의(레슨) 제목
     */
    title: string;
    /**
     * 강의(레슨) 순서
     */
    order: number;
    /**
     * 미리보기 여부
     */
    isPreview: boolean;
    /**
     * 강의(레슨) 재생 시간 (초)
     */
    duration?: number | null;
    /**
     * 강의(레슨) 설명
     */
    description?: string | null;
    /**
     * 영상 저장 정보 (JSON)
     */
    videoStorageInfo?: {
        [key: string]: unknown;
    } | null;
    /**
     * 강의 ID (UUID)
     */
    courseId: string;
    /**
     * 섹션 ID (UUID)
     */
    sectionId: string;
    /**
     * 강의 정보
     */
    course: Course;
    /**
     * 섹션 정보
     */
    section: Section;
};

export type Section = {
    /**
     * 섹션 ID (UUID)
     */
    id: string;
    /**
     * 섹션 제목
     */
    title: string;
    /**
     * 섹션 순서
     */
    order: number;
    /**
     * 섹션 설명
     */
    description?: string | null;
    /**
     * 강의 ID (UUID)
     */
    courseId: string;
    /**
     * 강의 정보
     */
    course: Course;
    /**
     * 강의 목록
     */
    lectures: Array<Lecture>;
};

export type CourseCategory = {
    /**
     * 카테고리 ID (UUID)
     */
    id: string;
    /**
     * 카테고리 이름
     */
    name: string;
    /**
     * 카테고리 슬러그
     */
    slug: string;
    /**
     * 카테고리 설명
     */
    description?: string | null;
    /**
     * 해당 카테고리의 강의 목록
     */
    courses: Array<Course>;
};

export type CourseEnrollment = {
    /**
     * 수강 신청 ID (UUID)
     */
    id: string;
    /**
     * 수강 신청 일시
     */
    enrollmentDate: string;
    /**
     * 사용자 ID (UUID)
     */
    userId: string;
    /**
     * 강의 ID (UUID)
     */
    courseId: string;
    /**
     * 수강생 정보
     */
    user: User;
    /**
     * 강의 정보
     */
    course: Course;
};

export type CourseReview = {
    /**
     * 수강평 ID (UUID)
     */
    id: string;
    /**
     * 수강평 내용
     */
    content: string;
    /**
     * 별점 (1-5)
     */
    rating: number;
    /**
     * 강사 답변
     */
    instructorReply?: string | null;
    /**
     * 작성자 ID (UUID)
     */
    userId: string;
    /**
     * 강의 ID (UUID)
     */
    courseId: string;
    /**
     * 작성자 정보
     */
    user: User;
    /**
     * 강의 정보
     */
    course: Course;
};

export type CourseComment = {
    /**
     * 댓글 ID (UUID)
     */
    id: string;
    /**
     * 댓글 내용
     */
    content: string;
    /**
     * 작성자 ID (UUID)
     */
    userId: string;
    /**
     * 질문 ID (UUID)
     */
    questionId: string;
    /**
     * 작성자 정보
     */
    user: User;
    /**
     * 질문 정보
     */
    courseQuestion: CourseQuestion;
};

export type CourseQuestion = {
    /**
     * 질문 ID (UUID)
     */
    id: string;
    /**
     * 질문 제목
     */
    title: string;
    /**
     * 질문 내용
     */
    content: string;
    /**
     * 작성자 ID (UUID)
     */
    userId: string;
    /**
     * 강의 ID (UUID)
     */
    courseId: string;
    /**
     * 작성자 정보
     */
    user: User;
    /**
     * 강의 정보
     */
    course: Course;
    /**
     * 댓글 목록
     */
    courseComments: Array<CourseComment>;
};

export type Course = {
    /**
     * 강의 ID (UUID)
     */
    id: string;
    /**
     * 강의 슬러그
     */
    slug: string;
    /**
     * 강의 제목
     */
    title: string;
    /**
     * 강의 가격
     */
    price: number;
    /**
     * 강의 난이도
     */
    level: string;
    /**
     * 강의 상태
     */
    status: string;
    /**
     * 강의 짧은 설명
     */
    shortDescription?: string | null;
    /**
     * 강의 상세 설명
     */
    description?: string | null;
    /**
     * 강의 썸네일 URL
     */
    thumbnail?: string | null;
    /**
     * 할인 가격
     */
    discountPrice?: number | null;
    /**
     * 강사 ID (UUID)
     */
    instructorId: string;
    /**
     * 강사 정보
     */
    instructor: User;
    /**
     * 섹션 목록
     */
    sections: Array<Section>;
    /**
     * 강의 목록
     */
    lectures: Array<Lecture>;
    /**
     * 강의 카테고리 목록
     */
    courseCategories: Array<CourseCategory>;
    /**
     * 수강 신청 목록
     */
    courseEnrollments: Array<CourseEnrollment>;
    /**
     * 강의 리뷰 목록
     */
    courseReviews: Array<CourseReview>;
    /**
     * 강의 질문 목록
     */
    courseQuestions: Array<CourseQuestion>;
};

export type LectureActivity = {
    /**
     * 강의 활동 로그 ID (UUID)
     */
    id: string;
    /**
     * 진행률 (0-100)
     */
    progress: number;
    /**
     * 완료 여부
     */
    isCompleted: boolean;
    /**
     * 마지막 시청 시간
     */
    lastWatchedAt: string;
    /**
     * 사용자 ID (UUID)
     */
    userId: string;
    /**
     * 강의 ID (UUID)
     */
    lectureId: string;
    /**
     * 사용자 정보
     */
    user: User;
    /**
     * 강의 정보
     */
    lecture: Lecture;
};

export type User = {
    /**
     * 사용자 ID (UUID)
     */
    id: string;
    /**
     * 사용자 이름
     */
    name?: {
        [key: string]: unknown;
    } | null;
    /**
     * 이메일 주소
     */
    email?: {
        [key: string]: unknown;
    } | null;
    /**
     * 이메일 인증 시간
     */
    emailVerified?: {
        [key: string]: unknown;
    } | null;
    /**
     * 해싱된 비밀번호
     */
    hashedPassword?: {
        [key: string]: unknown;
    } | null;
    /**
     * 사용자 프로필 이미지 URL
     */
    image?: {
        [key: string]: unknown;
    } | null;
    /**
     * 권한 ID (UUID)
     */
    roleId: string;
    /**
     * 사용자 권한 정보
     */
    role: Role;
    /**
     * 연결된 계정 목록
     */
    accounts: Array<Account>;
    /**
     * 개설한 강의 목록
     */
    courses: Array<Course>;
    /**
     * 수강 신청 목록
     */
    courseEnrollments: Array<CourseEnrollment>;
    /**
     * 작성한 강의 리뷰 목록
     */
    courseReviews: Array<CourseReview>;
    /**
     * 작성한 강의 질문 목록
     */
    courseQuestions: Array<CourseQuestion>;
    /**
     * 작성한 댓글 목록
     */
    courseComments: Array<CourseComment>;
    /**
     * 강의 활동 로그
     */
    lectureActivities: Array<LectureActivity>;
};

export type UpdateCourseDto = {
    /**
     * 코스 제목
     */
    title?: string;
    /**
     * 코스 가격
     */
    price?: number;
    /**
     * 코스 1~2줄 짧은 설명
     */
    shortDescription?: string;
    /**
     * 코스 상세페이지 설명
     */
    description?: string;
    /**
     * 썸네일 이미지 URL
     */
    thumbnailUrl?: string;
    /**
     * 코스 할인 가격
     */
    discountPrice?: number;
    /**
     * 코스 난이도
     */
    level?: string;
    /**
     * 코스 게시 여부
     */
    isPublished?: boolean;
    /**
     * 코스 카테고리 ID 목록
     */
    categoryIds?: Array<string>;
};

export type CreateSectionDto = {
    /**
     * 색션 제목
     */
    title: string;
};

export type UpdateSectionDto = {
    /**
     * 색션 제목
     */
    title?: string;
    /**
     * 섹션 설명
     */
    description?: string;
    /**
     * 섹션 순서
     */
    order?: number;
};

export type CreateLectureDto = {
    /**
     * 개별 강의 제목
     */
    title: string;
};

export type UpdateLectureDto = {
    /**
     * 개별 강의 제목
     */
    title?: string;
    /**
     * 개별 강의 설명
     */
    description?: string;
    /**
     * 개별 강의 순서
     */
    order?: number;
    /**
     * 개별 강의 길이
     */
    duration?: number;
    /**
     * 개별 강의 미리보기 여부
     */
    isPreview?: boolean;
    /**
     * 개별 강의 비디오 업로드 정보
     */
    videoStorageInfo?: {
        [key: string]: unknown;
    };
};

export type CreateCourseCategoryDto = {
    [key: string]: unknown;
};

export type UpdateCourseCategoryDto = {
    [key: string]: unknown;
};

export type CreateCourseEnrollmentDto = {
    [key: string]: unknown;
};

export type UpdateCourseEnrollmentDto = {
    [key: string]: unknown;
};

export type CreateCourseReviewDto = {
    [key: string]: unknown;
};

export type UpdateCourseReviewDto = {
    [key: string]: unknown;
};

export type CreateCourseQuestionDto = {
    [key: string]: unknown;
};

export type UpdateCourseQuestionDto = {
    [key: string]: unknown;
};

export type CreateCourseCommentDto = {
    [key: string]: unknown;
};

export type UpdateCourseCommentDto = {
    [key: string]: unknown;
};

export type CreateLectureActivityDto = {
    [key: string]: unknown;
};

export type UpdateLectureActivityDto = {
    [key: string]: unknown;
};

export type AuthControllerSignUpData = {
    body: SignUpDto;
    path?: never;
    query?: never;
    url: '/auth/sign-up';
};

export type AuthControllerSignUpErrors = {
    /**
     * 입력 데이터 유효성 검사 실패 또는 이메일 중복
     */
    400: unknown;
};

export type AuthControllerSignUpResponses = {
    /**
     * 회원가입 성공 (UserResponseDto 반환)
     */
    201: UserResponseDto;
};

export type AuthControllerSignUpResponse = AuthControllerSignUpResponses[keyof AuthControllerSignUpResponses];

export type AuthControllerSignInData = {
    body: SignInDto;
    path?: never;
    query?: never;
    url: '/auth/sign-in';
};

export type AuthControllerSignInErrors = {
    /**
     * 인증 실패 (비밀번호 불일치 등)
     */
    401: unknown;
};

export type AuthControllerSignInResponses = {
    /**
     * 로그인 성공 (Access Token 및 Refresh Token 쿠키 설정)
     */
    200: unknown;
};

export type AuthControllerSignOutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/sign-out';
};

export type AuthControllerSignOutResponses = {
    /**
     * 로그아웃 성공
     */
    200: unknown;
};

export type AuthControllerRefreshAccessTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/refresh-access';
};

export type AuthControllerRefreshAccessTokenErrors = {
    /**
     * Refresh Token이 유효하지 않거나 만료됨
     */
    401: unknown;
};

export type AuthControllerRefreshAccessTokenResponses = {
    /**
     * 재발급 성공
     */
    200: unknown;
};

export type AuthControllerGoogleLoginData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/google';
};

export type AuthControllerGoogleLoginResponses = {
    200: unknown;
};

export type AuthControllerGoogleCallbackData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/google/callback';
};

export type AuthControllerGithubLoginData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/github';
};

export type AuthControllerGithubLoginResponses = {
    200: unknown;
};

export type AuthControllerGithubCallbackData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/github/callback';
};

export type AuthControllerKakaoLoginData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/kakao';
};

export type AuthControllerKakaoLoginResponses = {
    200: unknown;
};

export type AuthControllerKakaoCallbackData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/kakao/callback';
};

export type RoleControllerCreateRoleData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/role';
};

export type RoleControllerCreateRoleErrors = {
    400: unknown;
};

export type RoleControllerCreateRoleResponses = {
    201: Role;
};

export type RoleControllerCreateRoleResponse = RoleControllerCreateRoleResponses[keyof RoleControllerCreateRoleResponses];

export type UserControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user';
};

export type UserControllerFindAllResponses = {
    200: unknown;
};

export type UserControllerCreateData = {
    body: CreateUserDto;
    path?: never;
    query?: never;
    url: '/user';
};

export type UserControllerCreateResponses = {
    201: unknown;
};

export type UserControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/user/{id}';
};

export type UserControllerRemoveResponses = {
    200: unknown;
};

export type UserControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/user/{id}';
};

export type UserControllerFindOneResponses = {
    200: unknown;
};

export type UserControllerUpdateData = {
    body: UpdateUserDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/user/{id}';
};

export type UserControllerUpdateResponses = {
    200: unknown;
};

export type AccountControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/account';
};

export type AccountControllerFindAllResponses = {
    200: unknown;
};

export type AccountControllerCreateData = {
    body: CreateAccountDto;
    path?: never;
    query?: never;
    url: '/account';
};

export type AccountControllerCreateResponses = {
    201: unknown;
};

export type AccountControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/account/{id}';
};

export type AccountControllerRemoveResponses = {
    200: unknown;
};

export type AccountControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/account/{id}';
};

export type AccountControllerFindOneResponses = {
    200: unknown;
};

export type AccountControllerUpdateData = {
    body: UpdateAccountDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/account/{id}';
};

export type AccountControllerUpdateResponses = {
    200: unknown;
};

export type VerificationTokenControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/verification-token';
};

export type VerificationTokenControllerFindAllResponses = {
    200: unknown;
};

export type VerificationTokenControllerCreateData = {
    body: CreateVerificationTokenDto;
    path?: never;
    query?: never;
    url: '/verification-token';
};

export type VerificationTokenControllerCreateResponses = {
    201: unknown;
};

export type VerificationTokenControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/verification-token/{id}';
};

export type VerificationTokenControllerRemoveResponses = {
    200: unknown;
};

export type VerificationTokenControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/verification-token/{id}';
};

export type VerificationTokenControllerFindOneResponses = {
    200: unknown;
};

export type VerificationTokenControllerUpdateData = {
    body: UpdateVerificationTokenDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/verification-token/{id}';
};

export type VerificationTokenControllerUpdateResponses = {
    200: unknown;
};

export type CourseControllerFindAllData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * 강의 제목 검색
         */
        title?: string;
        /**
         * 난이도 필터
         */
        level?: string;
        /**
         * 카테고리 ID 필터
         */
        categoryId?: string;
        /**
         * 건너뛸 개수 (Pagination)
         */
        skip?: number;
        /**
         * 가져올 개수 (Pagination)
         */
        take?: number;
    };
    url: '/course';
};

export type CourseControllerFindAllResponses = {
    200: Array<Course>;
};

export type CourseControllerFindAllResponse = CourseControllerFindAllResponses[keyof CourseControllerFindAllResponses];

export type CourseControllerCreateData = {
    body: CreateCourseDto;
    path?: never;
    query?: never;
    url: '/course';
};

export type CourseControllerCreateResponses = {
    /**
     * 생성된 코스 정보
     */
    201: Course;
};

export type CourseControllerCreateResponse = CourseControllerCreateResponses[keyof CourseControllerCreateResponses];

export type CourseControllerDeleteData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/course/{id}';
};

export type CourseControllerDeleteResponses = {
    /**
     * 삭제된 코스 정보
     */
    200: Course;
};

export type CourseControllerDeleteResponse = CourseControllerDeleteResponses[keyof CourseControllerDeleteResponses];

export type CourseControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        /**
         * 포함할 관계 정보. 허용된 값: sections, lectures, courseCategories, courseEnrollments, courseReviews, courseQuestions
         */
        include?: Array<string>;
    };
    url: '/course/{id}';
};

export type CourseControllerFindOneResponses = {
    200: Course;
};

export type CourseControllerFindOneResponse = CourseControllerFindOneResponses[keyof CourseControllerFindOneResponses];

export type CourseControllerUpdateData = {
    body: UpdateCourseDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/course/{id}';
};

export type CourseControllerUpdateResponses = {
    /**
     * 수정된 코스 정보
     */
    200: Course;
};

export type CourseControllerUpdateResponse = CourseControllerUpdateResponses[keyof CourseControllerUpdateResponses];

export type SectionControllerCreateData = {
    body: CreateSectionDto;
    path: {
        /**
         * 코스 ID
         */
        courseId: string;
    };
    query?: never;
    url: '/section/courses/{courseId}/sections';
};

export type SectionControllerCreateResponses = {
    /**
     * 섹션 생성 설명
     */
    200: Section;
};

export type SectionControllerCreateResponse = SectionControllerCreateResponses[keyof SectionControllerCreateResponses];

export type SectionControllerFindOneData = {
    body?: never;
    path: {
        /**
         * 섹션 ID
         */
        sectionId: string;
    };
    query?: never;
    url: '/section/sections/{sectionId}';
};

export type SectionControllerFindOneResponses = {
    /**
     * 섹션 상세 정보
     */
    200: Section;
};

export type SectionControllerFindOneResponse = SectionControllerFindOneResponses[keyof SectionControllerFindOneResponses];

export type SectionControllerRemoveData = {
    body?: never;
    path: {
        /**
         * 섹션 ID
         */
        sectionId: string;
    };
    query?: never;
    url: '/section/{sectionId}';
};

export type SectionControllerRemoveResponses = {
    /**
     * 섹션 삭제 성공
     */
    200: Section;
};

export type SectionControllerRemoveResponse = SectionControllerRemoveResponses[keyof SectionControllerRemoveResponses];

export type SectionControllerUpdateData = {
    body: UpdateSectionDto;
    path: {
        /**
         * 섹션 ID
         */
        sectionId: string;
    };
    query?: never;
    url: '/section/{sectionId}';
};

export type SectionControllerUpdateResponses = {
    /**
     * 섹션 업데이트 성공
     */
    200: Section;
};

export type SectionControllerUpdateResponse = SectionControllerUpdateResponses[keyof SectionControllerUpdateResponses];

export type LectureControllerCreateData = {
    body: CreateLectureDto;
    path: {
        /**
         * 섹션 ID
         */
        sectionId: string;
    };
    query?: never;
    url: '/lecture/sections/{sectionId}/lectures';
};

export type LectureControllerCreateResponses = {
    /**
     * 강의 생성 성공
     */
    200: Lecture;
};

export type LectureControllerCreateResponse = LectureControllerCreateResponses[keyof LectureControllerCreateResponses];

export type LectureControllerRemoveData = {
    body?: never;
    path: {
        /**
         * 개별 강의 ID
         */
        lectureId: string;
    };
    query?: never;
    url: '/lecture/{lectureId}';
};

export type LectureControllerRemoveResponses = {
    /**
     * 개별 강의 삭제 성공
     */
    200: Lecture;
};

export type LectureControllerRemoveResponse = LectureControllerRemoveResponses[keyof LectureControllerRemoveResponses];

export type LectureControllerFindOneData = {
    body?: never;
    path: {
        /**
         * 개별 강의 ID
         */
        lectureId: string;
    };
    query?: never;
    url: '/lecture/{lectureId}';
};

export type LectureControllerFindOneResponses = {
    /**
     * 개별 강의 상세 정보 조회
     */
    200: Lecture;
};

export type LectureControllerFindOneResponse = LectureControllerFindOneResponses[keyof LectureControllerFindOneResponses];

export type LectureControllerUpdateData = {
    body: UpdateLectureDto;
    path: {
        /**
         * 개별 강의 ID
         */
        lectureId: string;
    };
    query?: never;
    url: '/lecture/{lectureId}';
};

export type LectureControllerUpdateResponses = {
    /**
     * 개별 강의 수정 성공
     */
    200: Lecture;
};

export type LectureControllerUpdateResponse = LectureControllerUpdateResponses[keyof LectureControllerUpdateResponses];

export type CourseCategoryControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/course-category';
};

export type CourseCategoryControllerFindAllResponses = {
    200: unknown;
};

export type CourseCategoryControllerCreateData = {
    body: CreateCourseCategoryDto;
    path?: never;
    query?: never;
    url: '/course-category';
};

export type CourseCategoryControllerCreateResponses = {
    201: unknown;
};

export type CourseCategoryControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/course-category/{id}';
};

export type CourseCategoryControllerRemoveResponses = {
    200: unknown;
};

export type CourseCategoryControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/course-category/{id}';
};

export type CourseCategoryControllerFindOneResponses = {
    200: unknown;
};

export type CourseCategoryControllerUpdateData = {
    body: UpdateCourseCategoryDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/course-category/{id}';
};

export type CourseCategoryControllerUpdateResponses = {
    200: unknown;
};

export type CourseEnrollmentControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/course-enrollment';
};

export type CourseEnrollmentControllerFindAllResponses = {
    200: unknown;
};

export type CourseEnrollmentControllerCreateData = {
    body: CreateCourseEnrollmentDto;
    path?: never;
    query?: never;
    url: '/course-enrollment';
};

export type CourseEnrollmentControllerCreateResponses = {
    201: unknown;
};

export type CourseEnrollmentControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/course-enrollment/{id}';
};

export type CourseEnrollmentControllerRemoveResponses = {
    200: unknown;
};

export type CourseEnrollmentControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/course-enrollment/{id}';
};

export type CourseEnrollmentControllerFindOneResponses = {
    200: unknown;
};

export type CourseEnrollmentControllerUpdateData = {
    body: UpdateCourseEnrollmentDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/course-enrollment/{id}';
};

export type CourseEnrollmentControllerUpdateResponses = {
    200: unknown;
};

export type CourseReviewControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/course-review';
};

export type CourseReviewControllerFindAllResponses = {
    200: unknown;
};

export type CourseReviewControllerCreateData = {
    body: CreateCourseReviewDto;
    path?: never;
    query?: never;
    url: '/course-review';
};

export type CourseReviewControllerCreateResponses = {
    201: unknown;
};

export type CourseReviewControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/course-review/{id}';
};

export type CourseReviewControllerRemoveResponses = {
    200: unknown;
};

export type CourseReviewControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/course-review/{id}';
};

export type CourseReviewControllerFindOneResponses = {
    200: unknown;
};

export type CourseReviewControllerUpdateData = {
    body: UpdateCourseReviewDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/course-review/{id}';
};

export type CourseReviewControllerUpdateResponses = {
    200: unknown;
};

export type CourseQuestionControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/course-question';
};

export type CourseQuestionControllerFindAllResponses = {
    200: unknown;
};

export type CourseQuestionControllerCreateData = {
    body: CreateCourseQuestionDto;
    path?: never;
    query?: never;
    url: '/course-question';
};

export type CourseQuestionControllerCreateResponses = {
    201: unknown;
};

export type CourseQuestionControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/course-question/{id}';
};

export type CourseQuestionControllerRemoveResponses = {
    200: unknown;
};

export type CourseQuestionControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/course-question/{id}';
};

export type CourseQuestionControllerFindOneResponses = {
    200: unknown;
};

export type CourseQuestionControllerUpdateData = {
    body: UpdateCourseQuestionDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/course-question/{id}';
};

export type CourseQuestionControllerUpdateResponses = {
    200: unknown;
};

export type CourseCommentControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/course-comment';
};

export type CourseCommentControllerFindAllResponses = {
    200: unknown;
};

export type CourseCommentControllerCreateData = {
    body: CreateCourseCommentDto;
    path?: never;
    query?: never;
    url: '/course-comment';
};

export type CourseCommentControllerCreateResponses = {
    201: unknown;
};

export type CourseCommentControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/course-comment/{id}';
};

export type CourseCommentControllerRemoveResponses = {
    200: unknown;
};

export type CourseCommentControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/course-comment/{id}';
};

export type CourseCommentControllerFindOneResponses = {
    200: unknown;
};

export type CourseCommentControllerUpdateData = {
    body: UpdateCourseCommentDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/course-comment/{id}';
};

export type CourseCommentControllerUpdateResponses = {
    200: unknown;
};

export type LectureActivityControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/lecture-activity';
};

export type LectureActivityControllerFindAllResponses = {
    200: unknown;
};

export type LectureActivityControllerCreateData = {
    body: CreateLectureActivityDto;
    path?: never;
    query?: never;
    url: '/lecture-activity';
};

export type LectureActivityControllerCreateResponses = {
    201: unknown;
};

export type LectureActivityControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/lecture-activity/{id}';
};

export type LectureActivityControllerRemoveResponses = {
    200: unknown;
};

export type LectureActivityControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/lecture-activity/{id}';
};

export type LectureActivityControllerFindOneResponses = {
    200: unknown;
};

export type LectureActivityControllerUpdateData = {
    body: UpdateLectureActivityDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/lecture-activity/{id}';
};

export type LectureActivityControllerUpdateResponses = {
    200: unknown;
};
